webtalk_init -webtalk_dir C:/Users/Jim/Desktop/Code/Brainfuck/VHDL/BFISA/BFISA.sim/sim_2/behav/xsim/xsim.dir/sd_axi_tester_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Aug 25 00:22:10 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "3277e948-6288-4c01-8055-5377bf7e8158" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "57b9abab7a3b4c8abedc991da5a92385" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "13" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7800X CPU @ 3.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3504 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "13241805 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "34.92_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "16260_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3444193510 -regid "" -xml C:/Users/Jim/Desktop/Code/Brainfuck/VHDL/BFISA/BFISA.sim/sim_2/behav/xsim/xsim.dir/sd_axi_tester_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Jim/Desktop/Code/Brainfuck/VHDL/BFISA/BFISA.sim/sim_2/behav/xsim/xsim.dir/sd_axi_tester_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Jim/Desktop/Code/Brainfuck/VHDL/BFISA/BFISA.sim/sim_2/behav/xsim/xsim.dir/sd_axi_tester_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
